### ISSUE TITLE
Spersist-connect isn't updated to reflect the flexibility of spersist-store

### ISSUE THREAD

**Issue by Shotgunosine** [dmoracze/HPC_helper_tools#1]
Currently spersist-connect appears to break if you don't request a VNC tunnel, also, it doesn't support multiple ports. It'd be great if it could be updated to support that flexibility.

**Comment by dmoracze** [comment]
Added this fix/enhancement in 4581b814b384efc384cb30e57f57d06022bbfe73.

The script now reads .spersist to build the shh command. If VNC port exists, it will add it, otherwise it will not. Any number of tunnels are hopefully be supported. Still need to test multiple usecases.
